### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by yangdaowu** [yuzhouhe2000/Music_Source_Separator#1]
Hello, I am very happy to see the procedures you provide, which is very helpful to me. But I encountered some problems, when I training, I will appear：
![image](https://user-images.githubusercontent.com/64669901/124895585-40ba1400-e00f-11eb-8a1a-06070cce97b0.png)

The problem appeared in 98 lines：
![image](https://user-images.githubusercontent.com/64669901/124895562-3b5cc980-e00f-11eb-9f42-15411106d822.png)

I tried to modify：
![image](https://user-images.githubusercontent.com/64669901/124895734-62b39680-e00f-11eb-8d77-f9196744f889.png)

But encountered new problems：
![image](https://user-images.githubusercontent.com/64669901/124895788-7232df80-e00f-11eb-9712-485270c806a5.png)

How should I do？

**Comment by yuzhouhe2000** [comment]
Sorry currently the project is lack of error messages and comments. I think it can be a configuration issue. Are you using Conv-Tasnet? 

Also I notice “vocals” appear in the line 104 in your first screenshoot. You should change the separation task in General_config instead of train.py if you didn’t modify other part correspondingly.

<img width="586" alt="スクリーンショット 2021-07-12 午前0 36 13" src="https://user-images.githubusercontent.com/48540323/125203049-429f0400-e2a9-11eb-83d8-fcd5a6051f18.png”>

it is hard to tell what is the problem without more information. Maybe send me a screenshoot of your train_config?

**Comment by yangdaowu** [comment]
My train_config is like this:
![image](https://user-images.githubusercontent.com/64669901/125212463-27032000-e2e0-11eb-931f-99f5ff37330f.png)
Then I debug and I found that the value passed to Key has multiple paths:
![image](https://user-images.githubusercontent.com/64669901/125212507-721d3300-e2e0-11eb-8c41-e4d716016799.png)

**Comment by yuzhouhe2000** [comment]
Sorry I forgot to reply. Seems like your spectrograms variable has a path "A classic Education .... \\ vocals" as key instead of just "vocals." Maybe write a parser function and remove the path string before "\\". Sorry I only test it on linux, and the path variable is different on windows.
